version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    env_file: ./config/.backend.env
    build:
      context: .
      dockerfile: ./api/endpoints/backend.Dockerfile
    ports:
      - "5984:5984"
      - "5678:5678"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=rag_db
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
      - ./db:/app/db
    networks:
      - app_network

  frontend:
    env_file: ./config/.env
    build:
      context: .
      dockerfile: ./frontend/frontend.Dockerfile
    ports:
      - "3349:3349"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: